version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  test:
    docker:
      - image: cimg/node:18.0
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_POSTHOG_KEY: ${NEXT_PUBLIC_POSTHOG_KEY}
      NEXT_PUBLIC_WALLERCONNECTID: ${NEXT_PUBLIC_WALLERCONNECTID}
      NEXT_PUBLIC_ALCHEMY_KEY: ${NEXT_PUBLIC_ALCHEMY_KEY}
      SECRET_WORDS: ${SECRET_WORDS}
      NETWORK_NAME: ${NETWORK_NAME}
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install Playwright's dependencies
          command: npx playwright install --with-deps
      - run:
          name: Build
          command: |
            yarn db:generate:node
            yarn build:db:node
            yarn build:senate
      - browser-tools/install-browser-tools
      - run:
          name: Run Playwright tests
          command: xvfb-run --auto-servernum --server-num=1 npx playwright test
      - store_artifacts:
          path: playwright-report/
          destination: playwright-report
workflows:
  test_workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - dev
                - staging
