version: 2.1

jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright
    steps:
      - checkout
      - run:
          name: Install and build
          command: |
            npm install -g yarn
            yarn
            npx playwright install --with-deps chromium
            yarn db:generate:node
            yarn build:db:node
            yarn build:senate

      - run:
          name: Run test
          command: DEBUG=pw:browser xvfb-run npx playwright test

      - store_test_results:
          path: test-results

workflows:
  run-test-workflow:
    jobs:
      - run-test
