version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.34.0-jammy

    steps:
      - run:
          command: apt-get update && apt-get install -y dbus

      - checkout
      - node/install-packages:
          pkg-manager: yarn

      - browser-tools/install-chrome

      - run:
          name: Install Playwright's dependencies
          command: npx playwright install --with-deps

      - run:
          name: Install virtual display
          command: |
            apt-get install --no-install-recommends -y \
            fluxbox \
            xvfb

      - run:
          name: Build
          command: |
            yarn db:generate:node
            yarn build:db:node
            yarn build:senate

      - run:
          name: Run Playwright tests
          command: DEBUG=synpress:*,pw:browser,pw:api,pw:install PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml xvfb-run npx playwright test --reporter=junit

      - store_test_results:
          path: results.xml

      - store_artifacts:
          path: results.xml

workflows:
  test_workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - dev
                - staging
