version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1
  discord: antonioned/discord@0.1.0

jobs:
  build:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build
          command: |
            yarn build:db:node
            yarn build:senate

  setup_db:
    docker:
      - image: cimg/node:18.16.0
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: circleci
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          DATABASE_URL: mysql://root:root@localhost:3306/circleci
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Database Setup
          command: |
            yarn db:push
            yarn db:seed

  run_senate:
    docker:
      - image: cimg/node:18.16.0-browsers
    environment:
      DATABASE_URL: mysql://root:root@localhost:3306/circleci
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Senate
          command: yarn start:senate
          background: true

  run_tests:
    docker:
      - image: mcr.microsoft.com/playwright:v1.34.0-jammy
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - browser-tools/install-chrome
      - run:
          name: Install Playwright's dependencies
          command: npx playwright install --with-deps
      - run:
          name: Install virtual display
          command: |
            apt-get install --no-install-recommends -y \
            fluxbox \
            xvfb
      - run:
          name: Run Playwright tests
          no_output_timeout: 30m
          command: xvfb-run npx playwright test

  notify:
    docker:
      - image: cimg/node:18.16.0-browsers
    steps:
      - discord/status:
          failure_message: ":red_circle: **${CIRCLE_BRANCH}** tests failed."
          success_message: ":tada: ${CIRCLE_BRANCH} passed all tests."
          webhook: "${DISCORD_STATUS_WEBHOOK}"
          only_for_branches: "staging,dev"

workflows:
  test_workflow:
    jobs:
      - build
      - setup_db:
          requires:
            - build
      - run_senate:
          requires:
            - setup_db
      - run_tests:
          requires:
            - run_senate
      - notify:
          requires:
            - run_tests
