version: 2.1
orbs:
  discord: antonioned/discord@0.1.0
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.34.0-jammy
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: circleci
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
    environment:
      DATABASE_URL: mysql://root:root@localhost:3306/circleci
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Install Playwright's dependencies
          command: npx playwright install --with-deps

      - run:
          name: Install virtual display
          command: |
            apt-get install --no-install-recommends -y \
            fluxbox \
            xvfb

      - run:
          name: Build
          command: |
            yarn db:generate:node
            yarn build:db:node
            yarn db:push
            yarn db:seed
            yarn build:senate

      - run:
          environment:
            DEBUG: true
          name: Run Senate
          command: |
            yarn start:senate
          background: true

      - run:
          name: Run Playwright tests
          no_output_timeout: 30m
          command: xvfb-run npx playwright test

      - discord/status:
          failure_message: ":red_circle: **${CIRCLE_BRANCH}** tests failed."
          success_message: ":tada: ${CIRCLE_BRANCH} passed all tests."
          webhook: "${DISCORD_STATUS_WEBHOOK}"
          only_for_branches: "staging"
      - discord/status:
          failure_message: ":red_circle: **${CIRCLE_BRANCH}** tests failed."
          fail_only: true
          webhook: "${DISCORD_STATUS_WEBHOOK}"
          only_for_branches: "dev"
      - store_test_results:
          path: results.xml
      - store_artifacts:
          path: playwright-report/index.html
      - store_artifacts:
          path: test-results

workflows:
  test_workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - dev
                - staging
