version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.34.0-jammy
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-version: v1
      - run:
          name: Install and build
          command: |
            npx playwright install --with-deps chromium
            yarn db:generate:node
            yarn build:db:node
            yarn build:senate
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - .apps/senate/.next/cache
      - run:
          name: Run test
          command: npx playwright test
      - store_test_results:
          path: playwright-report/index.html

workflows:
  run-test-workflow:
    jobs:
      - run-test
