version: 2.1
orbs:
  discord: antonioned/discord@0.1.0
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.34.0-jammy
    steps:
      - checkout

      - run:
          name: Setup DB env
          command: |
            chmod -x prepareci.sh
            bash ./prepareci.sh

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Install Playwright's dependencies
          command: yarn playwright install --with-deps

      - run:
          name: Build
          command: |
            yarn db:generate:node
            yarn build:db:node
            yarn build:senate

      - run:
          name: Run Playwright tests
          no_output_timeout: 30m
          command: yarn test:e2e:ci

      - discord/status:
          failure_message: ":red_circle: **${CIRCLE_BRANCH}** tests failed."
          success_message: ":tada: ${CIRCLE_BRANCH} passed all tests."
          webhook: "${DISCORD_STATUS_WEBHOOK}"
          only_for_branches: "staging"
      - discord/status:
          failure_message: ":red_circle: **${CIRCLE_BRANCH}** tests failed."
          fail_only: true
          webhook: "${DISCORD_STATUS_WEBHOOK}"
          only_for_branches: "dev"
      - store_test_results:
          path: results.xml
      - store_artifacts:
          path: playwright-report/index.html
      - store_artifacts:
          path: test-results

workflows:
  test_workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - dev
                - staging
