[workspace]
members = [".",
    "prisma-cli"]

[package]
name = "detective"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
chrono = "0.4.24"
dotenv = "0.15.0"
env_logger = "0.10.0"
ethers = { version = "2.0.4", features = ["rustls", "openssl", "abigen"] }
futures = "0.3.28"
itertools = "0.10.5"
num-bigint = "0.4.3"
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.8", default-features = false, features = ["postgresql"] }
regex = "1.8.1"
reqwest = { version = "0.11.17", features = ["json"] }
reqwest-middleware = "0.2.1"
reqwest-retry = "0.2.2"
rocket = { version = "=0.5.0-rc.3", features = ["json"] }
serde = "1.0.163"
serde_json = "1.0.96"
tokio = { version = "1.28.1", features = ["full"] }

[build-dependencies]
ethers = { version = "2.0.4", features = ["rustls", "openssl", "abigen"] }
